
int-only:
	php7.4 test.php --int-script=../interpret/interpret.py --directory=tests/interpret-only --int-only --recursive
    # > test-int.html

error:
	php test.php --parse-only --int-only --recursive

